/**
 *
 * $Id$
 */
package pl.edu.agh.toik.aghbibtex.model.Bibtex.validation;


/**
 * A sample validator interface for {@link pl.edu.agh.toik.aghbibtex.model.Bibtex.Tag}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TagValidator {
	boolean validate();

	boolean validateName(String value);
}
